CREATE TABLE BIEN_TIPO (
    ID_BIEN          NUMBER NOT NULL,
    ID_TIPO_BIEN     NUMBER NOT NULL,
    -- Auditoría
    USUARIO_INGRESO  VARCHAR2(50) NOT NULL,
    FECHA_INGRESO    DATE DEFAULT SYSDATE NOT NULL,
    USUARIO_MODIFICA VARCHAR2(50),
    FECHA_MODIFICA   DATE,
    CONSTRAINT PK_BIEN_TIPO PRIMARY KEY (ID_BIEN, ID_TIPO_BIEN),
    CONSTRAINT FK_BT_BIEN FOREIGN KEY (ID_BIEN)
        REFERENCES BIEN(ID_BIEN),
    CONSTRAINT FK_BT_TIPO FOREIGN KEY (ID_TIPO_BIEN)
        REFERENCES TIPO_BIEN(ID_TIPO_BIEN)
);