-- TIPO_CARGO (rol especifico dentro del ministerio)
CREATE TABLE CARGO (
  ID                NUMBER PRIMARY KEY,
  IGLESIA_ID        NUMBER NOT NULL REFERENCES IGLESIA(ID),
  CODIGO            VARCHAR2(50)  NOT NULL,
  NOMBRE            VARCHAR2(150) NOT NULL,
  DESCRIPCION       VARCHAR2(300),
  ACTIVO            CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S','N')),
  -- Auditoría
  USUARIO_INGRESO   VARCHAR2(100),
  FECHA_INGRESO     DATE,
  USUARIO_MODIFICA  VARCHAR2(100),
  FECHA_MODIFICA    DATE,
  CONSTRAINT UQ_TIPO_CARGO_IG_COD UNIQUE (IGLESIA_ID, CODIGO)
);