CREATE TABLE CIERRE_MENSUAL_DET (
  ID                 NUMBER PRIMARY KEY,
  CIERRE_MENSUAL_ID  NUMBER NOT NULL REFERENCES CIERRE_MENSUAL(ID),
  CIERRE_DIARIO_ID   NUMBER NOT NULL REFERENCES CIERRE_DIARIO(ID),
  -- Auditoría
  USUARIO_INGRESO    VARCHAR2(100),
  FECHA_INGRESO      DATE,
  USUARIO_MODIFICA   VARCHAR2(100),
  FECHA_MODIFICA     DATE,
  CONSTRAINT UQ_CM_D UNIQUE (CIERRE_MENSUAL_ID, CIERRE_DIARIO_ID)
);