CREATE TABLE CIERRE_DIARIO (
  ID                NUMBER PRIMARY KEY,
  IGLESIA_ID        NUMBER NOT NULL REFERENCES IGLESIA(ID),
  FECHA             DATE NOT NULL,
  TOTAL_ENTRADAS    NUMBER(14,2) DEFAULT 0 NOT NULL,
  TOTAL_SALIDAS     NUMBER(14,2) DEFAULT 0 NOT NULL,
  TOTAL_NETO        NUMBER(14,2) DEFAULT 0 NOT NULL,
  OBSERVACION       VARCHAR2(300),
  -- Auditoría
  USUARIO_INGRESO   VARCHAR2(100),
  FECHA_INGRESO     DATE,
  USUARIO_MODIFICA  VARCHAR2(100),
  FECHA_MODIFICA    DATE,
  CONSTRAINT UQ_CIERRE_DIARIO UNIQUE (IGLESIA_ID, FECHA)
);