CREATE TABLE DET_MOVIMIENTO (
  ID                 NUMBER PRIMARY KEY,
  MOVIMIENTO_ID      NUMBER NOT NULL REFERENCES MOVIMIENTO(ID),
  TIPO_MOVIMIENTO_ID NUMBER NOT NULL REFERENCES TIPO_MOVIMIENTO(ID),
  MONTO              NUMBER(14,2) NOT NULL CHECK (MONTO > 0),
  DESCRIPCION        VARCHAR2(300),
  CIERRE_DIARIO_ID   NUMBER REFERENCES CIERRE_DIARIO(ID), -- se crea más abajo; FK se agrega luego
  -- Auditoría
  USUARIO_INGRESO    VARCHAR2(100),
  FECHA_INGRESO      DATE,
  USUARIO_MODIFICA   VARCHAR2(100),
  FECHA_MODIFICA     DATE
);