CREATE TABLE DET_EVENTO (
  ID                NUMBER PRIMARY KEY,
  EVENTO_ID         NUMBER NOT NULL REFERENCES EVENTO(ID),
  MIEMBRO_ID        NUMBER REFERENCES MIEMBRO(ID),
  NOMBRE_LIBRE      VARCHAR2(200), -- para visitantes no registrados
  ASISTIO           CHAR(1) DEFAULT 'S' CHECK (ASISTIO IN ('S','N')),
  ROL_EN_EVENTO     VARCHAR2(100), -- p.ej. predicador, músico, maestro, invitado
  OBSERVACION       VARCHAR2(300),
  -- Auditoría
  USUARIO_INGRESO   VARCHAR2(100),
  FECHA_INGRESO     DATE,
  USUARIO_MODIFICA  VARCHAR2(100),
  FECHA_MODIFICA    DATE,
  CONSTRAINT CK_DET_EVENTO_PERSONA CHECK (MIEMBRO_ID IS NOT NULL OR NOMBRE_LIBRE IS NOT NULL)
);