CREATE TABLE EVENTO (
  ID                NUMBER PRIMARY KEY,
  IGLESIA_ID        NUMBER NOT NULL REFERENCES IGLESIA(ID),
  TIPO_EVENTO_ID    NUMBER NOT NULL REFERENCES TIPO_EVENTO(ID),
  FECHA_HORA_INI    DATE NOT NULL,
  FECHA_HORA_FIN    DATE,
  LUGAR             VARCHAR2(200),
  DESCRIPCION       VARCHAR2(400),
  AFORO             NUMBER,
  ACTIVO            CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S','N')),
  -- Auditoría
  USUARIO_INGRESO   VARCHAR2(100),
  FECHA_INGRESO     DATE,
  USUARIO_MODIFICA  VARCHAR2(100),
  FECHA_MODIFICA    DATE
);