-- IGLESIA
CREATE TABLE IGLESIA (
  ID                NUMBER PRIMARY KEY,
  CODIGO            VARCHAR2(50)   NOT NULL,
  NOMBRE            VARCHAR2(200)  NOT NULL,
  ID_PAIS           NUMBER,
  ID_DEPTO          NUMBER,
  ID_MUNI           NUMBER,
  DIRECCION         VARCHAR2(300),
  LOGO              BLOB,
  TELEFONO          VARCHAR2(20),
  EMAIL             VARCHAR2(100),
  ACTIVO            CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S','N')),
  -- Auditoría
  USUARIO_INGRESO   VARCHAR2(100),
  FECHA_INGRESO     DATE,
  USUARIO_MODIFICA  VARCHAR2(100),
  FECHA_MODIFICA    DATE,
  CONSTRAINT UQ_IGLESIA_COD UNIQUE (CODIGO)
);
