-- Pertenencia de miembros a ministerios (muchos-a-muchos)
CREATE TABLE MIEMBRO_MINISTERIO (
  ID                NUMBER PRIMARY KEY,
  MIEMBRO_ID        NUMBER NOT NULL REFERENCES MIEMBRO(ID),
  MINISTERIO_ID     NUMBER NOT NULL REFERENCES MINISTERIO(ID),
  CARGO_ID          NUMBER NOT NULL REFERENCES CARGO(ID),
  FECHA_DESDE       DATE DEFAULT SYSDATE,
  FECHA_HASTA       DATE,
  ACTIVO            CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S','N')),
  -- Auditoría
  USUARIO_INGRESO   VARCHAR2(100),
  FECHA_INGRESO     DATE,
  USUARIO_MODIFICA  VARCHAR2(100),
  FECHA_MODIFICA    DATE,
  CONSTRAINT UQ_MIEMBRO_MIN UNIQUE (MIEMBRO_ID, MINISTERIO_ID, CARGO_ID)
);