CREATE TABLE MIEMBRO (
  ID                NUMBER PRIMARY KEY,
  IGLESIA_ID        NUMBER NOT NULL REFERENCES IGLESIA(ID),
  TIPO_PERSONA_ID   NUMBER NOT NULL REFERENCES TIPOS_PERSONA(ID),
  NOMBRES           VARCHAR2(100) NOT NULL,
  APELLIDOS         VARCHAR2(100) NOT NULL,
  GENERO            CHAR(1) CHECK (GENERO IN ('M','F')),
  FECHA_NAC         DATE,
  TELEFONO          VARCHAR2(30),
  EMAIL             VARCHAR2(150),
  FECHA_ALTA        DATE DEFAULT SYSDATE,
  BAUTIZADO         CHAR(1) DEFAULT 'N' CHECK (BAUTIZADO IN ('S','N')),
  ACTIVO            CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S','N')),
  -- Auditoría
  USUARIO_INGRESO   VARCHAR2(100),
  FECHA_INGRESO     DATE,
  USUARIO_MODIFICA  VARCHAR2(100),
  FECHA_MODIFICA    DATE
);