CREATE TABLE ROL (
  ID                NUMBER PRIMARY KEY,
  CODIGO            VARCHAR2(50)  NOT NULL,
  NOMBRE            VARCHAR2(100) NOT NULL,
  DESCRIPCION       VARCHAR2(300),
  ACTIVO            CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S','N')),
  -- Auditoría
  USUARIO_INGRESO   VARCHAR2(100),
  FECHA_INGRESO     DATE,
  USUARIO_MODIFICA  VARCHAR2(100),
  FECHA_MODIFICA    DATE,
  CONSTRAINT UQ_ROL_COD UNIQUE (CODIGO)
);