-- TIPO_MOVIMIENTO (diezmo, ofrenda, donación, gasto…)
CREATE TABLE TIPO_MOVIMIENTO (
  ID                NUMBER PRIMARY KEY,
  IGLESIA_ID        NUMBER NOT NULL REFERENCES IGLESIA(ID),
  CODIGO            VARCHAR2(50)  NOT NULL,
  NOMBRE            VARCHAR2(150) NOT NULL,
  INDICADOR         CHAR(1) NOT NULL CHECK (INDICADOR IN ('E','S')), -- E=Entrada, S=Salida
  DESCRIPCION       VARCHAR2(300),
  ACTIVO            CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S','N')),
  -- Auditoría
  USUARIO_INGRESO   VARCHAR2(100),
  FECHA_INGRESO     DATE,
  USUARIO_MODIFICA  VARCHAR2(100),
  FECHA_MODIFICA    DATE,
  CONSTRAINT UQ_TIPO_MOV_IG_COD UNIQUE (IGLESIA_ID, CODIGO)
);