CREATE TABLE TIPOS_PERSONA (
    ID                NUMBER,
    ID_IGLESIA      NUMBER NOT NULL,
    CODIGO            VARCHAR2(50)  NOT NULL,
    NOMBRE            VARCHAR2(100) NOT NULL,
    DESCRIPCION       VARCHAR2(300),
    ACTIVO            CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S','N')),
    -- Auditoría
    USUARIO_INGRESO   VARCHAR2(100),
    FECHA_INGRESO     DATE,
    USUARIO_MODIFICA  VARCHAR2(100),
    FECHA_MODIFICA    DATE,
    CONSTRAINT UQ_TIPOPER_COD UNIQUE (CODIGO),
    CONSTRAINT PK_TIPO_PERSONA PRIMARY KEY(ID),
    CONSTRAINT FK_TIPO_PERSONA_IGLESIA FOREIGN KEY(ID_IGLESIA) REFERENCES IGLESIA(ID)
);