CREATE TABLE USUARIO (
  ID                NUMBER PRIMARY KEY,
  IGLESIA_ID        NUMBER REFERENCES IGLESIA(ID),
  USERNAME          VARCHAR2(80)  NOT NULL,
  PASSWORD_HASH     VARCHAR2(200) NOT NULL,
  EMAIL             VARCHAR2(150),
  ACTIVO            CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S','N')),
  -- Auditoría
  USUARIO_INGRESO   VARCHAR2(100),
  FECHA_INGRESO     DATE,
  USUARIO_MODIFICA  VARCHAR2(100),
  FECHA_MODIFICA    DATE,
  CONSTRAINT UQ_USUARIO_USER UNIQUE (USERNAME)
);