CREATE TABLE USUARIO_ROL (
  ID                NUMBER PRIMARY KEY,
  USUARIO_ID        NUMBER NOT NULL REFERENCES USUARIO(ID),
  ROL_ID            NUMBER NOT NULL REFERENCES ROL(ID),
  -- Auditoría
  USUARIO_INGRESO   VARCHAR2(100),
  FECHA_INGRESO     DATE,
  USUARIO_MODIFICA  VARCHAR2(100),
  FECHA_MODIFICA    DATE,
  CONSTRAINT UQ_USUARIO_ROL UNIQUE (USUARIO_ID, ROL_ID)
);