CREATE OR REPLACE TRIGGER BIU_CIERRE_MENSUAL
BEFORE INSERT OR UPDATE ON CIERRE_MENSUAL
FOR EACH ROW
DECLARE l_user VARCHAR2(100);
BEGIN
  l_user := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
  IF INSERTING THEN
    IF :NEW.ID IS NULL THEN SELECT SEQ_CIERRE_MENSUAL.NEXTVAL INTO :NEW.ID FROM dual; END IF;
    :NEW.USUARIO_INGRESO := NVL(:NEW.USUARIO_INGRESO, l_user);
    :NEW.FECHA_INGRESO   := NVL(:NEW.FECHA_INGRESO, SYSDATE);
  END IF;
  IF UPDATING THEN
    :NEW.USUARIO_MODIFICA := l_user;
    :NEW.FECHA_MODIFICA   := SYSDATE;
  END IF;
END;
/